// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package workspacedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	DeleteWorkspace(ctx context.Context, id pgtype.UUID) error
	GetWorkspaceByID(ctx context.Context, id pgtype.UUID) (Workspace, error)
	GetWorkspaceBySlugAndOwner(ctx context.Context, arg GetWorkspaceBySlugAndOwnerParams) (Workspace, error)
	GetWorkspaces(ctx context.Context, userID pgtype.UUID) ([]Workspace, error)
	GetWorkspacesByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Workspace, error)
	UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error)
	UpdateWorkspaceStatus(ctx context.Context, arg UpdateWorkspaceStatusParams) error
}

var _ Querier = (*Queries)(nil)
