// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package invitationdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcceptWorkspaceInvitation(ctx context.Context, arg AcceptWorkspaceInvitationParams) (WorkspaceUserInvitation, error)
	GetMyInvitations(ctx context.Context, userID pgtype.UUID) ([]GetMyInvitationsRow, error)
	GetWorkspaceInvitation(ctx context.Context, id pgtype.UUID) (WorkspaceUserInvitation, error)
	InsertMember(ctx context.Context, arg InsertMemberParams) error
	RejectWorkspaceInvitation(ctx context.Context, id pgtype.UUID) (WorkspaceUserInvitation, error)
}

var _ Querier = (*Queries)(nil)
