// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package accessdb

import (
	"context"
)

type Querier interface {
	AddMember(ctx context.Context, arg AddMemberParams) (WorkspaceMember, error)
	InsertRole(ctx context.Context, arg InsertRoleParams) (WorkspaceRole, error)
}

var _ Querier = (*Queries)(nil)
