// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_groups.sql

package accessdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGroup = `-- name: CreateGroup :one
insert into workspace_groups
    (workspace_id, name, description)
values
    ($1, $2, $3)
returning id, workspace_id, name, description, created_at, updated_at
`

type CreateGroupParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Name        string      `json:"name"`
	Description *string     `json:"description"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (WorkspaceGroup, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.WorkspaceID, arg.Name, arg.Description)
	var i WorkspaceGroup
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :exec
delete from workspace_groups where id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroup, id)
	return err
}

const getGroup = `-- name: GetGroup :one
select id, workspace_id, name, description, created_at, updated_at from workspace_groups
where id = $1
`

func (q *Queries) GetGroup(ctx context.Context, id pgtype.UUID) (WorkspaceGroup, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i WorkspaceGroup
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroups = `-- name: GetGroups :many
select id, workspace_id, name, description, created_at, updated_at from workspace_groups
where workspace_id = $1
order by created_at
`

func (q *Queries) GetGroups(ctx context.Context, workspaceID pgtype.UUID) ([]WorkspaceGroup, error) {
	rows, err := q.db.Query(ctx, getGroups, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceGroup
	for rows.Next() {
		var i WorkspaceGroup
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroup = `-- name: UpdateGroup :one
update workspace_groups set 
    name = $2,
    description = $3,
    updated_at = now()
where id = $1
returning id, workspace_id, name, description, created_at, updated_at
`

type UpdateGroupParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description *string     `json:"description"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (WorkspaceGroup, error) {
	row := q.db.QueryRow(ctx, updateGroup, arg.ID, arg.Name, arg.Description)
	var i WorkspaceGroup
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
