// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_members.sql

package accessdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMember = `-- name: AddMember :one
insert into workspace_members
    (workspace_id, user_id, role_id, status)
values
    ($1, $2, $3, $4)
returning id, workspace_id, user_id, role_id, status, created_at, updated_at
`

type AddMemberParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
	RoleID      pgtype.UUID `json:"role_id"`
	Status      string      `json:"status"`
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, addMember,
		arg.WorkspaceID,
		arg.UserID,
		arg.RoleID,
		arg.Status,
	)
	var i WorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.RoleID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
