// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_roles.sql

package accessdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertRole = `-- name: InsertRole :one
insert into workspace_roles
    (workspace_id, name, permissions, is_system)
values
    ($1, $2, $3, $4)
returning id, workspace_id, name, permissions, is_system, created_at, updated_at
`

type InsertRoleParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Name        string      `json:"name"`
	Permissions []string    `json:"permissions"`
	IsSystem    bool        `json:"is_system"`
}

func (q *Queries) InsertRole(ctx context.Context, arg InsertRoleParams) (WorkspaceRole, error) {
	row := q.db.QueryRow(ctx, insertRole,
		arg.WorkspaceID,
		arg.Name,
		arg.Permissions,
		arg.IsSystem,
	)
	var i WorkspaceRole
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Permissions,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
