// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_group_member.sql

package accessdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteGroupMember = `-- name: DeleteGroupMember :exec
delete from workspace_group_members where
    group_id = $1 and member_id = $2
`

type DeleteGroupMemberParams struct {
	GroupID  pgtype.UUID `json:"group_id"`
	MemberID pgtype.UUID `json:"member_id"`
}

func (q *Queries) DeleteGroupMember(ctx context.Context, arg DeleteGroupMemberParams) error {
	_, err := q.db.Exec(ctx, deleteGroupMember, arg.GroupID, arg.MemberID)
	return err
}

const getGroupMembers = `-- name: GetGroupMembers :many
select
    gm.group_id, gm.member_id, gm.created_at,
    u.username,
    u.email,
    r.name as role_name,
    g.name as group_name
from
    workspace_group_members gm
left join
    workspace_groups g on g.id = gm.group_id
left join 
    workspace_members m on m.id = gm.member_id
left join
    users u on u.id = m.user_id
left join 
    workspace_roles r on r.id = m.role_id
where
    gm.group_id = $1
order by gm.created_at
`

type GetGroupMembersRow struct {
	GroupID   pgtype.UUID        `json:"group_id"`
	MemberID  pgtype.UUID        `json:"member_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Username  *string            `json:"username"`
	Email     *string            `json:"email"`
	RoleName  *string            `json:"role_name"`
	GroupName *string            `json:"group_name"`
}

func (q *Queries) GetGroupMembers(ctx context.Context, groupID pgtype.UUID) ([]GetGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, getGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupMembersRow
	for rows.Next() {
		var i GetGroupMembersRow
		if err := rows.Scan(
			&i.GroupID,
			&i.MemberID,
			&i.CreatedAt,
			&i.Username,
			&i.Email,
			&i.RoleName,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertGroupMember = `-- name: InsertGroupMember :one
insert into workspace_group_members
    (group_id, member_id)
values
    ($1, $2)
returning group_id, member_id, created_at
`

type InsertGroupMemberParams struct {
	GroupID  pgtype.UUID `json:"group_id"`
	MemberID pgtype.UUID `json:"member_id"`
}

func (q *Queries) InsertGroupMember(ctx context.Context, arg InsertGroupMemberParams) (WorkspaceGroupMember, error) {
	row := q.db.QueryRow(ctx, insertGroupMember, arg.GroupID, arg.MemberID)
	var i WorkspaceGroupMember
	err := row.Scan(&i.GroupID, &i.MemberID, &i.CreatedAt)
	return i, err
}
