// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package authdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username *string) (User, error)
	GetUserIdentity(ctx context.Context, arg GetUserIdentityParams) (UserIdentity, error)
	GetUsersById(ctx context.Context, dollar_1 []pgtype.UUID) ([]User, error)
	GetUsersByStatus(ctx context.Context, status string) ([]User, error)
	GetValidUserToken(ctx context.Context, arg GetValidUserTokenParams) (UserToken, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
