// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package authdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserIdentity(ctx context.Context, arg CreateUserIdentityParams) (UserIdentity, error)
	CreateUserToken(ctx context.Context, arg CreateUserTokenParams) (UserToken, error)
	DeleteExpiredUserTokens(ctx context.Context, userID pgtype.UUID) error
	DeleteTokensByType(ctx context.Context, arg DeleteTokensByTypeParams) error
	DeleteUserToken(ctx context.Context, arg DeleteUserTokenParams) error
	GetRefreshToken(ctx context.Context, codeHash string) (UserToken, error)
	GetTokenByCodeAndUser(ctx context.Context, arg GetTokenByCodeAndUserParams) (UserToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username *string) (User, error)
	GetUserIdentity(ctx context.Context, arg GetUserIdentityParams) (UserIdentity, error)
	GetUsersById(ctx context.Context, dollar_1 []pgtype.UUID) ([]User, error)
	GetUsersByStatus(ctx context.Context, status string) ([]User, error)
	GetValidUserToken(ctx context.Context, arg GetValidUserTokenParams) (UserToken, error)
	MarkRefreshTokenUsed(ctx context.Context, id pgtype.UUID) error
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdateStatus(ctx context.Context, arg UpdateStatusParams) (User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserToken(ctx context.Context, arg UpdateUserTokenParams) (UserToken, error)
}

var _ Querier = (*Queries)(nil)
