// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_tokens.sql

package authdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getValidUserToken = `-- name: GetValidUserToken :one
select id, user_id, type, code_hash, expires_at, used_at, created_at from user_tokens
where user_id = $1
    and type = $2
    and used_at is null
    and expires_at > now()
order by created_at desc
limit 1
`

type GetValidUserTokenParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Type   string      `json:"type"`
}

func (q *Queries) GetValidUserToken(ctx context.Context, arg GetValidUserTokenParams) (UserToken, error) {
	row := q.db.QueryRow(ctx, getValidUserToken, arg.UserID, arg.Type)
	var i UserToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}
