// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_identities.sql

package authdb

import (
	"context"
)

const getUserIdentity = `-- name: GetUserIdentity :one
select id, user_id, provider, provider_uid, email, created_at from user_identities
where provider = $1
    and provider_uid = $2
limit 1
`

type GetUserIdentityParams struct {
	Provider    string `json:"provider"`
	ProviderUid string `json:"provider_uid"`
}

func (q *Queries) GetUserIdentity(ctx context.Context, arg GetUserIdentityParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, getUserIdentity, arg.Provider, arg.ProviderUid)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUid,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}
